name: flutter_clean_domain_test
description: A package that provides a testing framework for packages that depends on flutter_clean_domain
version: 1.4.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mocktail: ^0.3.0

  flutter_clean_domain:
    git:
      url: git@github.com:fabriziocacicia/flutter_clean_domain.git
      ref: v1.2.0

  # Linting and Code analysis
  dart_lint_rules:
    git:
      url: git@github.com:fabriziocacicia/dart_lint_rules.git
      ref: v0.0.2
